# metamodel_version: 1.11.0
# version: 1.0.0
enum ROIBoundariesFormatTypeEnum
  {
    OME_Polygon
    OME_Mask
    Mesh_OBJ
    Mesh_STL
    Mesh_PLY
    GeoJSON
    WKT
    Label_Mask_Image
    Other
  }

enum SoftwareTypeEnum
  {
    Distance_Calculation
    DriftCorrection
    Precision_Assessment
    Segmentation
    Single_Molecule_Localization
    SpotLoc
    SpotLoc__PLUS_SIGN__Tracing
    Tracing
    Other
  }

enum TableNamespaceEnum
  {
    __4dn_FOF__HYPHEN_MINUS__CT_core
    __4dn_FOF__HYPHEN_MINUS__CT_demultiplexing
    __4dn_FOF__HYPHEN_MINUS__CT_trace
    __4dn_FOF__HYPHEN_MINUS__CT_rna
    __4dn_FOF__HYPHEN_MINUS__CT_quality
    __4dn_FOF__HYPHEN_MINUS__CT_rna_quality
    __4dn_FOF__HYPHEN_MINUS__CT_bio
    __4dn_FOF__HYPHEN_MINUS__CT_rna_bio
    __4dn_FOF__HYPHEN_MINUS__CT_cell
    __4dn_FOF__HYPHEN_MINUS__CT_extracell
    __4dn_FOF__HYPHEN_MINUS__CT_subcell
    __4dn_FOF__HYPHEN_MINUS__CT_mapping
    FOF__HYPHEN_MINUS__CT_vol_core
    FOF__HYPHEN_MINUS__CT_vol_quality
    FOF__HYPHEN_MINUS__CT_undecoded
  }

enum TimeUnitEnum
  {
    s
    sec
    ms
    msec
    min
    hr
  }

enum XYZUnitEnum
  {
    nm
    micron
    mm
  }

type Cell
  {
    cellId: Int!
    extraCellRoiId: Int
  }

type CellTable
  {
    fofCtVersion: String!
    tableNamespace: String!
    cellType: String!
    labName: String!
    experimenterName: String!
    experimenterContact: String!
    description: String!
    additionalTables: [TableNamespaceEnum]!
    extraCellRoiType: String
    softwares: [Software]
    xyzUnit: XYZUnitEnum!
    timeUnit: TimeUnitEnum
    intensityUnit: String
    intensityMeasurementMethod: String
    cells: [Cell]!
  }

type DemultiplexingTable
  {
    fofCtVersion: String!
    tableNamespace: String!
    labName: String!
    experimenterName: String!
    experimenterContact: String!
    description: String!
    softwares: [Software]!
    additionalTables: [TableNamespaceEnum]!
    xyzUnit: XYZUnitEnum!
    timeUnit: TimeUnitEnum
    intensityUnit: String
    intensityMeasurementMethod: String
    localizations: [Localization]!
  }

type ExtraCellROI
  {
    extraCellRoiId: Int!
  }

type ExtraCellROITable
  {
    fofCtVersion: String!
    tableNamespace: String!
    extraCellRoiType: String!
    labName: String!
    experimenterName: String!
    experimenterContact: String!
    description: String!
    additionalTables: [TableNamespaceEnum]!
    softwares: [Software]
    xyzUnit: XYZUnitEnum!
    timeUnit: TimeUnitEnum
    intensityUnit: String
    intensityMeasurementMethod: String
    extraCellRois: [ExtraCellROI]!
  }

type Localization implements LocalizationMixin
  {
    spotId: Int!
    channelName: String!
    fluorophoreName: String!
    locId: Int!
    x: Float!
    y: Float!
    z: Float!
  }

interface LocalizationMixin
  {
    locId: Int
    x: Float
    y: Float
    z: Float
  }

type RNASpot
  {
    rnaSpotId: Int!
    x: Float!
    y: Float!
    z: Float!
    rnaName: String!
    geneId: String!
    traceId: Int!
    transcriptId: String
    subCellRoiId: Int
    cellId: Int
    extraCellRoiId: Int
  }

type RNASpotBiologicalRecord
  {
    rnaSpotId: Int!
  }

type RNASpotBiologicalTable
  {
    fofCtVersion: String!
    tableNamespace: String!
    labName: String!
    experimenterName: String!
    experimenterContact: String!
    description: String!
    additionalTables: [TableNamespaceEnum]!
    softwares: [Software]
    xyzUnit: XYZUnitEnum!
    timeUnit: TimeUnitEnum
    intensityUnit: String
    intensityMeasurementMethod: String
    rnaSpotBiologicalRecords: [RNASpotBiologicalRecord]!
  }

type RNASpotQualityRecord
  {
    rnaSpotId: Int!
    channelName: String!
    fluorophoreName: String!
    xPrecision: Float
    yPrecision: Float
    zPrecision: Float
    photonCount: Int
    goodnessOfFit: Float
    centroidIntensity: Float
    peakIntensity: Float
    rawX: Float
    rawY: Float
    rawZ: Float
    xDrift: Float
    yDrift: Float
    zDrift: Float
    xChromaticShift: Float
    yChromaticShift: Float
    zChromaticShift: Float
    xLocError: Float
    yLocError: Float
    zLocError: Float
  }

type RNASpotQualityTable
  {
    fofCtVersion: String!
    tableNamespace: String!
    labName: String!
    experimenterName: String!
    experimenterContact: String!
    description: String!
    additionalTables: [TableNamespaceEnum]!
    softwares: [Software]
    xyzUnit: XYZUnitEnum!
    timeUnit: TimeUnitEnum
    intensityUnit: String
    intensityMeasurementMethod: String
    rnaSpotQualityRecords: [RNASpotQualityRecord]!
  }

type RNASpotTable
  {
    fofCtVersion: String!
    tableNamespace: String!
    genomeAssembly: String!
    geneIdType: String!
    xyzUnit: XYZUnitEnum!
    labName: String!
    experimenterName: String!
    experimenterContact: String!
    description: String!
    softwares: [Software]!
    additionalTables: [TableNamespaceEnum]!
    transcriptIdType: String
    rnaSpots: [RNASpot]!
  }

type ROIMapping
  {
    subCellRoiId: Int
    cellId: Int
    extraCellRoiId: Int
    roiBoundaries: String!
  }

type ROIMappingTable
  {
    fofCtVersion: String!
    tableNamespace: String!
    roiBoundariesFormatType: ROIBoundariesFormatTypeEnum!
    xyzUnit: XYZUnitEnum!
    labName: String!
    experimenterName: String!
    experimenterContact: String!
    description: String!
    additionalTables: [TableNamespaceEnum]!
    roiBoundariesFormatDescription: String
    cellType: String
    subCellRoiType: String
    extraCellRoiType: String
    softwares: [Software]
    timeUnit: TimeUnitEnum
    intensityUnit: String
    intensityMeasurementMethod: String
    roiMappings: [ROIMapping]!
  }

type SMLocalization implements LocalizationMixin
  {
    spotId: Int!
    traceId: Int!
    chrom: String!
    chromStart: Int!
    chromEnd: Int!
    subCellRoiId: Int
    cellId: Int
    extraCellRoiId: Int
    locId: Int!
    x: Float!
    y: Float!
    z: Float!
  }

type SMLocalizationQualityRecord
  {
    locId: Int!
    channelName: String!
    fluorophoreName: String!
    xPrecision: Float
    yPrecision: Float
    zPrecision: Float
    photonCount: Int
    goodnessOfFit: Float
    centroidIntensity: Float
    peakIntensity: Float
    rawX: Float
    rawY: Float
    rawZ: Float
    xLocError: Float
    yLocError: Float
    zLocError: Float
  }

type SMLocalizationQualityTable
  {
    fofCtVersion: String!
    tableNamespace: String!
    labName: String!
    experimenterName: String!
    experimenterContact: String!
    description: String!
    softwares: [Software]!
    additionalTables: [TableNamespaceEnum]!
    xyzUnit: XYZUnitEnum!
    timeUnit: TimeUnitEnum
    intensityUnit: String
    intensityMeasurementMethod: String
    smLocalizationQualityRecords: [SMLocalizationQualityRecord]!
  }

type SMLocalizationTable
  {
    fofCtVersion: String!
    tableNamespace: String!
    labName: String!
    experimenterName: String!
    experimenterContact: String!
    description: String!
    softwares: [Software]!
    additionalTables: [TableNamespaceEnum]!
    genomeAssembly: String!
    modification: String
    vcfFileName: String
    vcfVersion: String
    xyzUnit: XYZUnitEnum!
    timeUnit: TimeUnitEnum
    intensityUnit: String
    intensityMeasurementMethod: String
    smLocalizations: [SMLocalization]!
  }

type Software
  {
    softwareTitle: String!
    softwareType: SoftwareTypeEnum!
    softwareAuthors: String!
    softwareDescription: String!
    softwareParameters: String!
    softwareRepository: String!
    softwarePreferredCitationId: String!
  }

type SpotBiologicalRecord
  {
    spotId: Int!
  }

type SpotBiologicalTable
  {
    fofCtVersion: String!
    tableNamespace: String!
    labName: String!
    experimenterName: String!
    experimenterContact: String!
    description: String!
    additionalTables: [TableNamespaceEnum]!
    softwares: [Software]
    xyzUnit: XYZUnitEnum!
    timeUnit: TimeUnitEnum
    intensityUnit: String
    intensityMeasurementMethod: String
    spotBiologicalRecords: [SpotBiologicalRecord]!
  }

type SpotQualityRecord
  {
    spotId: Int!
    channelName: String!
    fluorophoreName: String!
    xPrecision: Float
    yPrecision: Float
    zPrecision: Float
    photonCount: Int
    goodnessOfFit: Float
    centroidIntensity: Float
    peakIntensity: Float
    rawX: Float
    rawY: Float
    rawZ: Float
    xDrift: Float
    yDrift: Float
    zDrift: Float
    xChromaticShift: Float
    yChromaticShift: Float
    zChromaticShift: Float
    xLocError: Float
    yLocError: Float
    zLocError: Float
  }

type SpotQualityTable
  {
    fofCtVersion: String!
    tableNamespace: String!
    labName: String!
    experimenterName: String!
    experimenterContact: String!
    description: String!
    additionalTables: [TableNamespaceEnum]!
    softwares: [Software]
    xyzUnit: XYZUnitEnum!
    timeUnit: TimeUnitEnum
    intensityUnit: String
    intensityMeasurementMethod: String
    spotQualityRecords: [SpotQualityRecord]!
  }

type SubCellROI
  {
    subCellRoiId: Int!
    cellId: Int
  }

type SubCellROITable
  {
    fofCtVersion: String!
    tableNamespace: String!
    subCellRoiType: String!
    labName: String!
    experimenterName: String!
    experimenterContact: String!
    description: String!
    additionalTables: [TableNamespaceEnum]!
    cellType: String
    softwares: [Software]
    xyzUnit: XYZUnitEnum!
    timeUnit: TimeUnitEnum
    intensityUnit: String
    intensityMeasurementMethod: String
    subCellRois: [SubCellROI]!
  }

type Trace
  {
    traceId: Int!
  }

type TraceTable
  {
    fofCtVersion: String!
    tableNamespace: String!
    labName: String!
    experimenterName: String!
    experimenterContact: String!
    description: String!
    additionalTables: [TableNamespaceEnum]!
    softwares: [Software]
    xyzUnit: XYZUnitEnum!
    timeUnit: TimeUnitEnum
    intensityUnit: String
    intensityMeasurementMethod: String
    traces: [Trace]!
  }

type UndecodedLocalization implements LocalizationMixin
  {
    hybId: Int!
    imageFrameId: Int!
    channelName: String!
    fluorophoreName: String!
    theZ: Int
    locId: Int!
    x: Float!
    y: Float!
    z: Float!
  }

type UndecodedLocalizationTable
  {
    fofCtVersion: String!
    tableNamespace: String!
    labName: String!
    experimenterName: String!
    experimenterContact: String!
    description: String!
    softwares: [Software]!
    additionalTables: [TableNamespaceEnum]!
    xyzUnit: XYZUnitEnum!
    timeUnit: TimeUnitEnum
    intensityUnit: String
    intensityMeasurementMethod: String
    undecodedLocalizations: [UndecodedLocalization]!
  }
